name: OasisChat
main: net.charter.orion_pax.OasisChat.OasisChat
version: 2.10242013_B1511
description: A player/staff chat system for bukkit servers!
author: Paxination
commands:
  a:
    description: Admin chat
    usage:
    permission: oasischat.staff.a
    permission-message: You don't have permissions for <permission>
    
  p:
    description: Party chat
    usage:
    permission: oasischat.players.p
    permission-message: You don't have permissions for <permission>
    
  party:
    description: Party chat
    usage:
    permission: oasischat.players.party
    permission-message: You don't have permissions for <permission>
    
  staff:
    description: Lists all online staff members
    usage:
    permission: oasischat.staff.staff
    permission-message: You don't have permissions for <permission>
    
  listparties:
    description: Party list for staff
    usage: "Usage: /<command>"
    permission: oasischat.staff.listparties
    permission-message: You don't have permissions for <permission>
    
  pspyoff:
    description: Quits spying on a party chat
    usage: "Usage: /<command>"
    permission: oasischat.staff.pspyoff
    permission-message: You don't have permissions for <permission>
    
  pspyon:
    description: Allows staff to silently join a party chat
    usage: "Usage: /<command> <partychatname>"
    permission: oasischat.staff.pspyon
    permission-message: You don't have permissions for <permission>
    
  psay:
    description: Allows staff to chat in a party chat
    usage: "Usage: /<command> Your message here!"
    permission: oasischat.staff.psay
    permission-message: You don't have permissions for <permission>
    
  partyinfo:
    description: Gives Staff info about a partychat.
    usage: "Usage: /<command> <partychatname> (party name not needed if already in party spy!)"
    permission: oasischat.staff.partyinfo
    permission-message: You don't have permissions for <permission>
    
  oasischat:
    description:  Additional commands for OasisChat!
    permission: oasischat.staff.oasischat
    permission-message: You don't have permissions for <permission>
    
  credits:
    description: List of beta testers
    permission: oasischat.players.credits
        
permissions:
    oasischat.staff.*:
        description: Gives access to all staff commands
        children:
            oasischat.staff.a: true
            oasischat.staff.staff: true
            oasischat.staff.psay: true
            oasischat.staff.pspyon: true
            oasischat.staff.pspyoff: true
            oasischat.staff.listparties: true
            oasischat.staff.partyinfo: true
            
    oasischat.player:
        description: Player chat commands
        children:
            oasischat.players.p: true
            oasischat.players.party: true
            oasischat.players.credits: true
